### ISSUE TITLE
Keep getting this strange error.

### ISSUE THREAD

**Issue by sameet** [kcakdemir/HiCPlotter#12]
Hi, 
I am trying to plot data generated using Dr. Servant's pipeline.  I am using the following command line:

`python ~/GitHub/HiCPlotter/HiCPlotter.py -f iced/40000/S1_003_40000_iced.matrix -n S1_003 -tri 1 -bed raw/40000/S1_003_40000_ord.bed -r 40000 -chr chr12 -s 50000 -e 51000 -hmc 5 -ptd 1 -pi 1 -o ../../analysis-nov142016/S1_003-plot`

I keep getting the following strange error, is am I doing anything wrong?

`Traceback (most recent call last):
  File "/Users/sameet/GitHub/HiCPlotter/HiCPlotter.py", line 1741, in <module>
    HiCplotter(**args)
  File "/Users/sameet/GitHub/HiCPlotter/HiCPlotter.py", line 1136, in HiCplotter
    ax4.plot(np.arange(start,end),nums,'black')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 4137, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 317, in _grab_next_args
    for seg in self._plot_args(remaining, kwargs):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 295, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 237, in _xy_from_xy
    raise ValueError("x and y must have same first dimension")
ValueError: x and y must have same first dimension`

**Comment by kcakdemir** [comment]
Which genomic location are you trying to plot?
Lets say for chr12:4000-12000 you should use -s 1 -e 3 with 40000 resolution...

**Comment by sameet** [comment]
Aah, so the bin number is wrt chromosome, not the absolute bin number from
the bed file?

**Comment by kcakdemir** [comment]
yes, that's correct...
