### ISSUE TITLE
numpy error

### ISSUE THREAD

**Issue by skytguuu** [kcakdemir/HiCPlotter#27]
Hi,

When I tried to use HiCPlotter, it reported an error that: 
###
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "/share/home/Garen/softwares/HiCPlotter-master/HiCPlotter.py", line 17, in <module>
    from mpl_toolkits.axes_grid1 import make_axes_locatable
  File "/share/home/Garen/anaconda2/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/__init__.py", line 6, in <module>
    from . import axes_size as Size
  File "/share/home/Garen/anaconda2/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_size.py", line 19, in <module>
    from matplotlib.axes import Axes
  File "/share/home/Garen/anaconda2/lib/python2.7/site-packages/matplotlib/axes/__init__.py", line 4, in <module>
    from ._subplots import *
  File "/share/home/Garen/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_subplots.py", line 7, in <module>
    from matplotlib.gridspec import GridSpec, SubplotSpec
  File "/share/home/Garen/anaconda2/lib/python2.7/site-packages/matplotlib/gridspec.py", line 26, in <module>
    import matplotlib.transforms as mtransforms
  File "/share/home/Garen/anaconda2/lib/python2.7/site-packages/matplotlib/transforms.py", line 39, in <module>
    from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
ImportError: numpy.core.multiarray failed to import
#####
Then I updated my numpy version, but it did not work. Could you give me a hand?

Thank you!

**Comment by kcakdemir** [comment]
Hi,
I think the issue is with matplotlib version so updating matplotlib's version could solve the problem. Best - kadir
