### ISSUE TITLE
plot multiple bed files as bar plots below the matrix

### ISSUE THREAD

**Issue by girdhar3** [kcakdemir/HiCPlotter#36]
I am trying to plot H3K27ac peaks, H3K4me3 peaks and TAD regions below the matrix              
 python HiCPlotter.py -f $file  -chr chr22 -o Example -r 10000 -n Neuron_PFC -s 1800 -e 4000 -o Example -ptd 1 -pcd 3 -pcdf $TAD,$H3K4me3_peaks,$H3K27ac_peaks -pdb 1 -ptr 1

I am getting this error

Traceback (most recent call last):
  File "HiCPlotter.py", line 2171, in <module>
    HiCplotter(**args)
  File "HiCPlotter.py", line 663, in HiCplotter
    matrix,nums,tricks=read_HiCdata(files[exp],fileHeader,fileFooter,cleanNANs,smoothNoise,window,tadRange,plotInsulation,plotTadDomains,randomBins)
  File "HiCPlotter.py", line 61, in read_HiCdata
    if plotInsulation or plotTadDomains and not randomBins: nums,tricks=insulation(matrix,ins_window,rel_window)
  File "HiCPlotter.py", line 503, in insulation
    if current[0] not in pBorders and current[0]+1 not in regions: pBorders.append(current[0])
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by girdhar3** [comment]
when I do this

python HiCPlotter.py -f $file -chr chr22 -o Example -r 10000 -n Neuron_PFC -s 1800 -e 4000 -o Example -pcd 1 -pcdf $TAD $H3K4me3_peaks $H3K27ac_peaks

It gives Upps!! Please provide equal number of HiC matrix and custom domains

**Comment by kcakdemir** [comment]
Hi,
If you'd like to plot your data as bar plots then you should use "--barPlots"
python HiCPlotter.py -f $file -chr chr22 -o Example -r 10000 -n Neuron_PFC -s 1800 -e 4000 -o Example -ptd 1 -bl TAD,K4me3,K27Ac -b $TAD,$H3K4me3_peaks,$H3K27ac_peaks -pdb 1 -ptr 1
